export const simlish: Record<string, string> = {
  "awesome": "litzergam",
  "away": "araganda",
  "baby": "nooboo",
  "bad": "frabbit",
  "bed": "bweb",
  "bored": "awasa poa",
  "boulevard": "boo leyar",
  "cat": "flicka",
  "celebration": "woohoo",
  "cheers": "shuno",
  "cheese": "chasha",
  "congrats": "veena fredishay",
  "congratulations": "veena fredishay",
  "cool": "yibs",
  "dance": "shooflee",
  "doctor": "doctork",
  "dog": "woofum",
  "drink": "shuno",
  "excuse": "befnuh",
  "expression": "bibbidi",
  "fire": "fliblia",
  "food": "chumcha",
  "fortune": "mazel",
  "friend": "chumcha",
  "fuck": "woohoo",
  "fun": "litzergam",
  "good": "gah",
  "goodbye": "dag dag",
  "hello": "sul sul",
  "hi": "stoba",
  "hungry": "feebee lay",
  "in": "im",
  "is": "iz",
  "it": "it",
  "kiss": "chee noob",
  "love": "woob",
  "luck": "mazel",
  "milk": "laloo",
  "money": "baloobas",
  "music": "blaza",
  "my": "ma",
  "night": "noop",
  "no": "neh",
  "ohbaby": "oh feebee lay!",
  "okay": "hasha",
  "park": "par",
  "pizza": "chumcha",
  "pregnant": "pooba",
  "sex": "woohoo",
  "sing": "singa",
  "small": "squib",
  "sorry": "sool sool",
  "stranger": "stamby",
  "surprise": "badoodle",
  "thanks": "sherb",
  "there's": "zerpa",
  "there": "zerpa",
  "tomorrow": "merinae",
  "what's up": "whippna choba dog",
  "wow": "zow",
  "yes": "yibbs",
  "you:": "voo",
}
